site_name: wknk-doc-python
site_author: wasknk    
repo_url: https://github.com/YourUsername/YourRepoName 

theme:
    name: readthedocs      
    highlightjs: true       

nav:
    - 首页: 'index.md'      
    - 脚本教程指南: 'guide.md' 
    - Docker Usage: 'docker.md'
    - Alembic: 'alembic.md'
    - Jupyter Notebook: 'JupyterNotebook.md'
    - Git: 'git.md'
    - Wsl: 'wsl.md'
    - Wraps: 'wraps.md'